<?php

// This file has been auto-generated by the Symfony Dependency Injection Component for internal use.

if (\class_exists(\ContainerGrFh4xP\Shopware_Production_KernelDevDebugContainer::class, false)) {
    // no-op
} elseif (!include __DIR__.'/ContainerGrFh4xP/Shopware_Production_KernelDevDebugContainer.php') {
    touch(__DIR__.'/ContainerGrFh4xP.legacy');

    return;
}

if (!\class_exists(Shopware_Production_KernelDevDebugContainer::class, false)) {
    \class_alias(\ContainerGrFh4xP\Shopware_Production_KernelDevDebugContainer::class, Shopware_Production_KernelDevDebugContainer::class, false);
}

return new \ContainerGrFh4xP\Shopware_Production_KernelDevDebugContainer([
    'container.build_hash' => 'GrFh4xP',
    'container.build_id' => '73d10b1b',
    'container.build_time' => 1631177244,
], __DIR__.\DIRECTORY_SEPARATOR.'ContainerGrFh4xP');
